### ISSUE TITLE
New Pod version for swift 4.2

### ISSUE THREAD

**Issue by s4cha** [HHK1/PryntTrimmerView#37]
Hi @HHK1 

We are encountering an issue with Swift 4.2 on our picker. https://github.com/Yummypets/YPImagePicker/issues/224 

After some research, it looks like we'd need to have a pod version uploaded for PryntTrimmerView in swift 4.2.

Trying to link the dependency from the tag`3.0.0-beta.1` doesn't work for some reason unfortunately :/

```ruby
[!] Invalid `YPImagePicker.podspec` file: [!] Unsupported version requirements.

 #  from /Users/sacha/Projects/YPImagePicker/YPImagePicker.podspec:16
 #  -------------------------------------------
 #    s.dependency 'SteviaLayout', '~> 4.4.0'
 >    s.dependency 'PryntTrimmerView', :git => 'https://github.com/HHK1/PryntTrimmerView.git', :tag => '3.0.0-beta.1'
 #    s.resources    = ['Resources/*', 'Source/**/*.xib']
 #  -------------------------------------------
```

I think you'd need to push a new version for instance `2.1.0` based on 3.0.0-beta.1 code `then pod trunk push`.

Thanks a ton for your help :)

**Comment by HHK1** [comment]
Yes, I believe that Carthage does not support tags marked as pre-release. Have you tried pointing at the latest commit on master ?
I'll take a look at this hopefully today, otherwise tomorrow

**Comment by s4cha** [comment]
@HHK1, Carthage works fine actually. The issue is only with Cocoapods.
I don't remember if I tried using commits so I can give it a shot tomorrow in the meantime.
Let me know if I can be of any help on this ;)

**Comment by NikKovIos** [comment]
The `:branch => 'master'` instead of `:tag` doesn't work as well.
That's because the PryntTrimmerView is by `prynt` in cocoapods : https://cocoapods.org/pods/PryntTrimmerView  
And it's not registered there as HHK1, so the cocoapods doesn't see that pod. You need to trunk the pod with HHK1 AFAK.
🙂

**Comment by billandr** [comment]
@s4cha update the YPImagePicker.podspec to remove the source location; you can't do that.
s.dependency 'PryntTrimmerView', '~> 3.0.0'

**Comment by HHK1** [comment]
@NikKovIos Good catch, I recently transferred ownership, but haven't made that change yet

**Comment by s4cha** [comment]
@billandr Thanks for chiming in, I believe the latest version up is 2.0.1 though https://cocoapods.org/pods/PryntTrimmerView

**Comment by HHK1** [comment]
I've published a new tagged version, with the pre-built framework for Carthage. Sadly I can't publish the release on the trunk, I don't have access to my prynt.co email. 
I'll see how I can regain access, can you try with the latest tag in the meantime ?

**Comment by NikKovIos** [comment]
` >    s.dependency 'PryntTrimmerView', :git => 'https://github.com/HHK1/PryntTrimmerView.git', :tag => '3.0.0'` still doesn't work

**Comment by HHK1** [comment]
Hmm, pointing to the master branch or the tag inside your Podfile will work if you use directly the pod in your project, but that it is not possible to do this when defining a pod dependency.
See: https://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of/22475228#22475228

I've filed a claim to regain ownership of the project, once it is resolved, I'll be able to publish the tag on cocoapods. Sorry for the inconvenience.

**Comment by NikKovIos** [comment]
We can cope your lib inside ours. What do you think about it?

**Comment by HHK1** [comment]
Yes I agree with @s4cha, it should be resolved very soon, so I don't think it's necessary. Transitioning to new versions of Swift always take some time :)

**Comment by NikKovIos** [comment]
Ok, i just suggested)

**Comment by s4cha** [comment]
Sometimes I dream of a world where everybody uses Carthage xD.

**Comment by billandr** [comment]
> Yeah looks like dependencies can't point to specific git repos, it has to be up in the master pod repository. @HHK1 no problem, these things happen ! We are actually using your work so thank You 🙏

exactly - but you can still point the source elsewhere by making sure that you declare the Pod before declaring the pod that has the dependency and it will use the "Name" as a key/value pair and pull down whatever version you want.

**Comment by NikKovIos** [comment]
Carthage have a one big disadvantage - u can't fastly correct code and debug, like you can with cocoapods.

**Comment by jlaws** [comment]
+1

**Comment by HHK1** [comment]
https://cocoapods.org/pods/PryntTrimmerView, version 3.0.0 has been published

**Comment by HHK1** [comment]
@s4cha @NikKovIos Once you confirm everything works for you, you can close this issue

**Comment by s4cha** [comment]
Works on my side 🚀 , Thanks a ton for your help on this @HHK1 🙏

**Comment by s4cha** [comment]
@jlaws @billandr is that good on your side as well?

**Comment by billandr** [comment]
> @jlaws @billandr is that good on your side as well?

it always worked on my end because I had to fork to a private repo anyway for a missing feature that allows the app too provide the initial start / end point.

**Comment by jlaws** [comment]
Works great, thank you!
